/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sptech.school.guardian.angel.project;

import com.github.britooo.looca.api.core.Looca;

/**
 *
 * @author MBC
 */
public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Propiedades
     */
    public Sistema() {
        initComponents();
        exibirPropriedades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        propiedadesTextArea = new javax.swing.JTextArea();
        textoPropiedades = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Guardian Angel");
        setMinimumSize(new java.awt.Dimension(320, 418));
        setResizable(false);
        getContentPane().setLayout(null);

        propiedadesTextArea.setBackground(new java.awt.Color(204, 204, 204));
        propiedadesTextArea.setColumns(20);
        propiedadesTextArea.setRows(5);
        propiedadesTextArea.setEnabled(false);
        jScrollPane1.setViewportView(propiedadesTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 280, 280);

        textoPropiedades.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        textoPropiedades.setForeground(new java.awt.Color(0, 0, 0));
        textoPropiedades.setText("Propriedades:");
        getContentPane().add(textoPropiedades);
        textoPropiedades.setBounds(100, 30, 130, 24);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }
    Looca looca = new Looca();
    public void exibirPropriedades(){
        propiedadesTextArea.setText(looca.getSistema().toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea propiedadesTextArea;
    private javax.swing.JLabel textoPropiedades;
    // End of variables declaration//GEN-END:variables
}
